# Generated by Django 3.0.7 on 2020-06-19 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 16, 35, 38, 785888), verbose_name='date published'),
        ),
    ]
